install.packages("car")
install.packages("Publish")
library(car)
library(Publish)
tabll <- data.frame(crime_table_info_numeric, nominal_zp_info_numeric_integer, number_of_schools_info_numeric)
corMatrix <- cor(tabll)
print(corMatrix)
fit <- lm(crime_table_info_numeric~nominal_zp_info_numeric_integer+number_of_schools_info_numeric)
scatterplotMatrix(tabll,spread = FALSE, lty.smooth = 2, main ='Соотношение переменных')
summary(fit)
print(fit)
confint(fit)
aov(fit)
