install.packages("car")
install.packages("Publish")
library(car)
library(Publish)
tabll <- data.frame(lifespan_info_numeric, nominal_zp_info_numeric_integer, doctors_info_numeric)
corMatrix <- cor(tabll)
print(corMatrix)
fit <- lm(lifespan_info_numeric~medium_zarplata+doctors_info_numeric)
scatterplotMatrix(tabll,spread = FALSE, lty.smooth = 2, main ='Соотношение переменных')
summary(fit)
print(fit)
confint(fit)
aov(fit)
